### ISSUE TITLE
Node.js Live Bangalore

### ISSUE THREAD

**Issue by mikeal** [nodeschool/bangalore#7]
Hiya :)

The Node.js Foundation is running an event in Bangalore in March. http://live.nodejs.org/events/bangalore.html

We're looking for speakers and would love people from the Bangalore NodeSchool community to apply. https://github.com/nodejs/live.nodejs.org#interested-in-speaking

If you have any other questions just let me know ;)

**Comment by tarungarg546** [comment]
Cant this event be shifted because at that time(19-20 March) we have a hell lot of events in Bangalore(Few i can recall is India Hacks Developer Conference at Vivanta Taj  , kranky webRTC conference with google at MLR convention center , Intel iot roadshow and hackathon , google iwg meet and lot more) + there is festive season around that time in North India .
If this event can be postponed by a week atleast , it would be beneficial for our community as well  .
Because as a member we dont want to miss this or any technical event happening in the city and sometime people had to choose between couple good events by some big players like google,Kranky , Thoughtworks , Intel or Node.JS foundation and that's not a good situation for any tech savy person. So again i request you to look into if this event can be postponed by atleast a week.

**Comment by mikeal** [comment]
Unfortunately we have to this in March and the partner company that is hosting it, Wipro, requested this date :(

Sounds like there's a lot going on Bangalore right now :) The community in Bangalore appears to be pretty huge though, our metrics have it as one of the top cities for Node.js users in the world, so it's probably a good thing that there are multiple events because capacity at each one is limited.

**Comment by tarungarg546** [comment]
What i am saying is , you can still do this in March , but still can try
talking to Wipro over this so that we can have this event on 26-27 March
may be they will agree .
And in a city like Bangalore you will always find lots of things happening
but what matters is quality over quantity & all the events happening on
19th March are un-argueably top in quality . So it becomes always difficult
to what to choose over what and there is always a second thought that by
not going to certain place we might be missing something awesome so that
second thought is what always haunts as a developer and we can be in
catch-22 .
Also why i am saying all this is because i am commited to some other event
and dont want to miss this event also :( . So , can you try?

**Comment by mikeal** [comment]
Unfortunately the last week of March is CollabSummit and all the foundation people have to be there :(

**Comment by tarungarg546** [comment]
Would the event videos will be put online on youtube & who is keynote
speaker for this event?

**Comment by mikeal** [comment]
Ashley Williams is speaking. I'm not sure about the videos yet, if the talks are recorded they will definitely end up on the nodejs youtube channel though.

**Comment by tarungarg546** [comment]
And what is the topic of talk of Ashley?

**Comment by mikeal** [comment]
@tarungarg546 I'm not entirely sure yet, she did a talk a few nights ago in LA about all the great features in npm that you probably don't know about :) she'll also be running a NodeTogether workshop in Bangalore.

@ashleywilliams do you know what you're talking about yet?

**Comment by somsharan** [comment]
Node Live was good attended as participant, We couldn't get anyone from bengaluru nodeschool group to talk as a speaker. hope to get in future.

**Comment by mikeal** [comment]
Event has happened, closed :)
